services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: oidc
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data