services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: forum
      POSTGRES_PASSWORD: forum
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data