services:
  db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: forum
      POSTGRES_PASSWORD: forum
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway:7.11.4
    platform: linux/amd64
    command: -url=jdbc:postgresql://db:5432/forum -schemas=public -user=forum -password=forum -connectRetries=60 migrate
    volumes:
      - ./db/migration:/flyway/sql
    depends_on:
      - db