openapi: 3.0.3
info:
  title: Forum API
  description: >-
    API documentation for a forum with multiple boards, posts, and comments,
    using JWT for authentication.
  version: 1.0.0
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://redocly.github.io/openapi-template/logo.png'
tags:
  - name: Users
    description: User operations
  - name: Boards
    description: Board operations
  - name: Posts
    description: Post operations
  - name: Comments
    description: Comment operations
servers:
  - url: http://localhost:8080
    description: Local development server
security:
  - BearerAuth: []
paths:
  /users:
    $ref: paths/users.yml
  /users/{userId}:
    $ref: paths/users_{userId}.yml
  /boards:
    $ref: paths/boards.yml
  /boards/{boardId}:
    $ref: paths/boards_{boardId}.yml
  /boards/{boardId}/posts:
    $ref: paths/boards_{boardId}_posts.yml
  /posts/{postId}:
    $ref: paths/posts_{postId}.yml
  /posts/{postId}/comments:
    $ref: paths/posts_{postId}_comments.yml
  /comments/{commentId}:
    $ref: paths/comments_{commentId}.yml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
